#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODEL_PATH="${MODEL_PATH:-/mnt/sfs_turbo/models/Qwen3.5-4B}"
HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-8016}"
TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-4}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.85}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-36864}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-36864}"
MM_PROCESSOR_CACHE_GB="${MM_PROCESSOR_CACHE_GB:-20}"
API_SERVER_PROFILE_DIR="${API_SERVER_PROFILE_DIR:-/tmp/api_server_profiles}"
API_SERVER_PROFILE_HEADER="${API_SERVER_PROFILE_HEADER:-x-profile-api-server}"
API_SERVER_PROFILE_HEADER_VALUE="${API_SERVER_PROFILE_HEADER_VALUE:-1}"
API_SERVER_PROFILE_ENDPOINT_REGEX="${API_SERVER_PROFILE_ENDPOINT_REGEX:-^/v1/chat/completions$}"
API_SERVER_PROFILE_DUMP_TEXT="${API_SERVER_PROFILE_DUMP_TEXT:-1}"
API_SERVER_PROFILE_DUMP_HTML="${API_SERVER_PROFILE_DUMP_HTML:-1}"
API_SERVER_PROFILE_DUMP_FUNCTIONS="${API_SERVER_PROFILE_DUMP_FUNCTIONS:-1}"
API_SERVER_PROFILE_TIMELINE="${API_SERVER_PROFILE_TIMELINE:-1}"
API_SERVER_PROFILE_INTERVAL="${API_SERVER_PROFILE_INTERVAL:-0.0001}"
ALLOWED_LOCAL_MEDIA_PATH="${ALLOWED_LOCAL_MEDIA_PATH:-}"
ENFORCE_EAGER="${ENFORCE_EAGER:-0}"

source /usr/local/Ascend/ascend-toolkit/set_env.sh

export ASCEND_RT_VISIBLE_DEVICES="${ASCEND_RT_VISIBLE_DEVICES:-0,1,2,3}"
export HCCL_BUFFSIZE="${HCCL_BUFFSIZE:-1024}"
export HCCL_OP_EXPANSION_MODE="${HCCL_OP_EXPANSION_MODE:-AIV}"
export CPU_AFFINITY_CONF="${CPU_AFFINITY_CONF:-1}"
export VLLM_USE_V1="${VLLM_USE_V1:-1}"
export VLLM_ASCEND_ENABLE_PREFETCH_MLP="${VLLM_ASCEND_ENABLE_PREFETCH_MLP:-1}"
export VLLM_ASCEND_ENABLE_NZ="${VLLM_ASCEND_ENABLE_NZ:-1}"
export PYTORCH_NPU_ALLOC_CONF="${PYTORCH_NPU_ALLOC_CONF:-expandable_segments:True}"
export API_SERVER_PROFILE_DIR
export API_SERVER_PROFILE_HEADER
export API_SERVER_PROFILE_HEADER_VALUE
export API_SERVER_PROFILE_ENDPOINT_REGEX
export API_SERVER_PROFILE_DUMP_TEXT
export API_SERVER_PROFILE_DUMP_HTML
export API_SERVER_PROFILE_DUMP_FUNCTIONS
export API_SERVER_PROFILE_TIMELINE
export API_SERVER_PROFILE_INTERVAL

cmd=(
  python "$SCRIPT_DIR/run_vllm_api_server_profiled.py"
  serve "$MODEL_PATH"
  --host "$HOST"
  --port "$PORT"
  --tensor-parallel-size "$TENSOR_PARALLEL_SIZE"
  --gpu-memory-utilization "$GPU_MEMORY_UTILIZATION"
  --max-model-len "$MAX_MODEL_LEN"
  --max-num-batched-tokens "$MAX_NUM_BATCHED_TOKENS"
  --async-scheduling
  --additional-config '{"enable_cpu_binding": true}'
  --mm-processor-cache-type shm
  --mm-processor-cache-gb "$MM_PROCESSOR_CACHE_GB"
  --mm-encoder-tp-mode data
)

if [[ -n "$ALLOWED_LOCAL_MEDIA_PATH" ]]; then
  cmd+=(--allowed-local-media-path "$ALLOWED_LOCAL_MEDIA_PATH")
fi

if [[ "$ENFORCE_EAGER" == "1" ]]; then
  cmd+=(--enforce-eager)
fi

exec "${cmd[@]}" "$@"
